#!/bin/sh
#
# ~/.xprofile
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Set keyboard layout:
setxkbmap gb

# Colorscheme
#BASE16_SHELL="$HOME/.config/base16-shell/base16-pop.dark.sh"
#[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
xrdb "$HOME/.Xresources"

# Multi monitor support:
#
~/.screenlayout/screen.sh

# Set default browser:
export BROWSER=chromium
